repos:
  - repo: local
    hooks:
      - id: requirements_cli
        name: Requirements CLI
        entry: poetry export --format=requirements.txt --without-hashes --output=pyinstaller/requirements-cli.txt
        pass_filenames: false
        language: system

      - id: requirements_gui
        name: Requirements GUI
        entry: poetry export --format=requirements.txt --without-hashes -E gui --output=pyinstaller/requirements-gui.txt
        pass_filenames: false
        language: system

      - id: isort
        name: isort
        stages: [ commit ]
        language: system
        entry: poetry run isort
        types: [ python ]

      - id: black
        name: black
        stages: [ commit ]
        language: system
        entry: poetry run black
        types: [ python ]

      - id: flake8
        name: flake8
        stages: [ commit ]
        language: system
        entry: poetry run flake8
        types: [ python ]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [ commit ]
        language: system
        entry: poetry run mypy
        types: [ python ]
        pass_filenames: false

