name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '(deps') }}

    steps:
      - uses: actions/checkout@v4

      - name: Package GUI Application for Windows
        uses: yshalsager/pyinstaller-action-windows@main
        with:
          path: .
          spec: shamela2epubgui.spec
          requirements: requirements-gui.txt

      - name: Package CLI Application for Windows
        uses: yshalsager/pyinstaller-action-windows@main
        with:
          path: .
          spec: shamela2epub.spec
          requirements: requirements-cli.txt

      - uses: actions/upload-artifact@v4
        if: github.actor != 'dependabot[bot]'
        with:
          name: shamela2epubgui.exe
          path: dist/windows

      - uses: actions/upload-artifact@v4
        if: github.actor != 'dependabot[bot]'
        with:
          name: shamela2epub.exe
          path: dist/windows

      - name: Package GUI Application for Linux
        uses: yshalsager/pyinstaller-action-linux@main
        with:
          path: .
          spec: shamela2epubgui.spec
          requirements: requirements-gui.txt

      - name: Package CLI Application for Linux
        uses: yshalsager/pyinstaller-action-linux@main
        with:
          path: .
          spec: shamela2epub.spec
          requirements: requirements-cli.txt

      - uses: actions/upload-artifact@v4
        if: github.actor != 'dependabot[bot]'
        with:
          name: shamela2epub
          path: dist/linux

      - uses: actions/upload-artifact@v4
        if: github.actor != 'dependabot[bot]'
        with:
          name: shamela2epubgui
          path: dist/linux

      - name: Set release name to tag name or datetime
        id: release
        run: |
          echo ${{ github.ref }}
          ref='refs/tags/v'
          if [[ ${{ github.ref }} == *${ref}* ]]; then
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          else
            echo "version=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Release
        if: github.actor != 'dependabot[bot]' && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.version }}
          name: ${{ steps.release.outputs.version }}
          files: |
            dist/windows/shamela2epub.exe
            dist/linux/shamela2epub
            dist/windows/shamela2epubgui.exe
            dist/linux/shamela2epubgui
