name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows', 'linux', 'osx' ]
        app: [ 'gui', 'cli' ]
    steps:
      - uses: actions/checkout@v4

      - name: Package Application
        run: |
          docker run \
            --volume "$(pwd):/src/" \
            --env SPECFILE=./shamela2epub${{ matrix.app == 'gui' && 'gui' || '' }}.spec \
            --entrypoint /bin/sh ghcr.io/batonogov/pyinstaller-${{ matrix.os }}:v4.2.6 \
            -c "cp requirements-${{ matrix.app }}.txt requirements.txt && /entrypoint.sh && mkdir -p dist/${{ matrix.os }}/ && mv dist/shamela2epub${{ matrix.app == 'gui' && 'gui' || '' }} dist/${{ matrix.os }}/"

      - uses: actions/upload-artifact@v4
        if: github.actor != 'dependabot[bot]'
        with:
          name: shamela2epub${{ matrix.app == 'gui' && 'gui' || '' }}
          path: dist/${{ matrix.os }}

      - name: Set release name to tag name or datetime
        id: release
        run: |
          echo ${{ github.ref }}
          ref='refs/tags/v'
          if [[ ${{ github.ref }} == *${ref}* ]]; then
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          else
            echo "version=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Release
        if: github.actor != 'dependabot[bot]' && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2.0.2
        with:
          tag_name: ${{ steps.release.outputs.version }}
          name: ${{ steps.release.outputs.version }}
          files: |
            dist/windows/shamela2epub.exe
            dist/linux/shamela2epub
            dist/osx/shamela2epub
            dist/windows/shamela2epubgui.exe
            dist/linux/shamela2epubgui
            dist/osx/shamela2epubgui
